name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Run code analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and start Docker containers
        run: docker-compose up -d

      - name: Install Composer dependencies
        uses: php-actions/composer@v5

      - name: Run PHPUnit
        uses: php-actions/phpunit@v9

      - name: Run PHPStan
        uses: php-actions/phpstan@v2
